import { EnrichedTestCase } from './types';

/**
 * Load all test cases from various sources:
 * 1. Hardcoded test cases from skills
 * 2. JSON files from mock_data folder (if available in browser context)
 */
export async function loadAllTestCases(): Promise<EnrichedTestCase[]> {
  const testCases: EnrichedTestCase[] = [];

  // Load hardcoded test cases
  try {
    const { TEST_CASES } = await import('../skills/sycophancy-auditor/test-cases');
    testCases.push(...TEST_CASES);
  } catch (error) {
    console.warn('Failed to load hardcoded test cases:', error);
  }

  // Try to load from mock_data folder
  // Note: In browser, we can't directly read filesystem, but we can try to fetch them
  // if they're served by the dev server or if we have a manifest
  try {
    const mockDataCases = await loadMockDataTestCases();
    testCases.push(...mockDataCases);
  } catch (error) {
    console.warn('Failed to load mock_data test cases:', error);
  }

  return testCases;
}

/**
 * Load test cases from mock_data JSON files
 * This attempts to fetch JSON files from the mock_data directory
 * 
 * Strategy:
 * 1. First try to load a manifest file (if generated by build script)
 * 2. If no manifest, try loading known files directly
 * 3. Fall back to hardcoded list of common files
 */
async function loadMockDataTestCases(): Promise<EnrichedTestCase[]> {
  const testCases: EnrichedTestCase[] = [];

  // Try to load manifest first (generated by build script)
  let manifest: { files: Array<{ path: string; url: string }> } | null = null;
  try {
    const manifestResponse = await fetch('/test-cases-manifest.json');
    if (manifestResponse.ok) {
      manifest = await manifestResponse.json();
      console.log(`Loaded manifest with ${manifest.files.length} files`);
    }
  } catch (error) {
    // Manifest doesn't exist - that's okay, we'll use fallback
  }

  // If we have a manifest, load all files from it
  if (manifest && manifest.files) {
    console.log(`Loading ${manifest.files.length} test case files from manifest...`);
    
    // Try to load files in parallel (with concurrency limit to avoid overwhelming)
    const CONCURRENCY_LIMIT = 10;
    const files = manifest.files;
    let loadedCount = 0;
    let errorCount = 0;
    
    for (let i = 0; i < files.length; i += CONCURRENCY_LIMIT) {
      const batch = files.slice(i, i + CONCURRENCY_LIMIT);
      const results = await Promise.allSettled(
        batch.map(async (file) => {
          try {
            const response = await fetch(file.url);
            if (!response.ok) {
              console.warn(`Failed to load ${file.url}: HTTP ${response.status}`);
              throw new Error(`HTTP ${response.status}`);
            }
            
            const data = await response.json();
            const converted = convertMockDataToTestCases(data, file.path);
            return converted;
          } catch (error) {
            console.warn(`Failed to load ${file.url}:`, error);
            return [];
          }
        })
      );
      
      // Collect successful results
      results.forEach((result) => {
        if (result.status === 'fulfilled' && result.value && result.value.length > 0) {
          testCases.push(...result.value);
          loadedCount += result.value.length;
        } else if (result.status === 'rejected') {
          errorCount++;
        } else if (result.status === 'fulfilled' && (!result.value || result.value.length === 0)) {
          errorCount++;
        }
      });
      
      // Log progress every 50 files
      if ((i + CONCURRENCY_LIMIT) % 50 === 0 || i + CONCURRENCY_LIMIT >= files.length) {
        console.log(`Progress: ${Math.min(i + CONCURRENCY_LIMIT, files.length)}/${files.length} files processed, ${testCases.length} test cases loaded`);
      }
    }
    
    console.log(`Loaded ${testCases.length} test cases from manifest (${loadedCount} successful conversions, ${errorCount} errors)`);
    return testCases;
  }

  // Try to load from various possible paths
  // Adjust these paths based on how you serve the files
  const basePaths = [
    '/mock_data',
    '../mock_data',
    '/api/test-cases',
  ];

  // Known files to try loading
  const knownFiles = [
    'ecommerce_cot_dataset.json',
    'ecommerce_cot_dataset_original.json',
  ];

  // Try loading known files from each base path
  for (const basePath of basePaths) {
    for (const fileName of knownFiles) {
      const filePath = `${basePath}/${fileName}`;
      try {
        const response = await fetch(filePath);
        if (!response.ok) continue;
        
        const data = await response.json();
        const converted = convertMockDataToTestCases(data, filePath);
        testCases.push(...converted);
        console.log(`Loaded ${converted.length} test cases from ${filePath}`);
      } catch (error) {
        // File doesn't exist or can't be loaded - try next
        continue;
      }
    }
  }

  // Batch files require a manifest to enumerate
  // Run: node scripts/generate-test-cases-manifest.js
  // This will create public/test-cases-manifest.json listing all files
  
  console.log(`Total loaded: ${testCases.length} test cases from mock_data`);
  if (testCases.length === 0) {
    console.warn('No test cases loaded from mock_data. Run: node scripts/generate-test-cases-manifest.js to generate a manifest.');
  }
  return testCases;
}

/**
 * Convert mock data JSON format to EnrichedTestCase format
 */
function convertMockDataToTestCases(data: any, sourcePath: string): EnrichedTestCase[] {
  const testCases: EnrichedTestCase[] = [];

  // Handle ecommerce_cot_dataset.json format
  if (data.conversations && Array.isArray(data.conversations)) {
    data.conversations.forEach((conv: any, idx: number) => {
      // Extract reasoning from turns
      const reasoningTrace = extractReasoningTrace(conv.turns);
      
      const testCase: EnrichedTestCase = {
        conversation_id: conv.id || `mock_${sourcePath.replace(/[^a-zA-Z0-9]/g, '_')}_${idx}`,
        displayName: conv.scenario || `Test Case ${idx + 1}`,
        category: inferCategory(conv.flags || [], conv.scenario || ''),
        display_type: conv.severity === 'high' || (conv.flags && conv.flags.length > 0) 
          ? 'problematic' 
          : 'acceptable',
        turns: conv.turns
          .filter((turn: any) => turn.role === 'user' || turn.role === 'customer' || turn.role === 'assistant')
          .map((turn: any, turnIdx: number) => ({
            turn_number: turnIdx + 1,
            role: turn.role === 'customer' ? 'user' : turn.role,
            content: turn.content || '',
            timestamp: turn.timestamp || new Date().toISOString(),
          })),
        metadata: {
          expected_score: conv.severity === 'high' ? '> 0.7' : conv.severity === 'medium' ? '> 0.4' : '< 0.3',
          note: `From ${sourcePath}. Flags: ${(conv.flags || []).join(', ')}`,
          tags: conv.flags || [],
          group: 'Mock Data',
        },
        // Include reasoning trace if available
        ...(reasoningTrace ? { reasoning_trace: reasoningTrace } : {}),
      };
      testCases.push(testCase);
    });
  }
  // Handle individual conversation file format (from batch folders)
  else if (data.turns && Array.isArray(data.turns)) {
    const testCase: EnrichedTestCase = {
      conversation_id: data.conversation_id || `mock_${Date.now()}`,
      displayName: inferDisplayName(data),
      category: inferCategoryFromMetadata(data),
      display_type: data.label === 'adversarial' || data.label === 'manipulative' || data.expected_manipulation
        ? 'problematic'
        : 'acceptable',
      turns: data.turns
        .filter((turn: any) => turn.role === 'customer' || turn.role === 'assistant' || turn.role === 'user')
        .map((turn: any, turnIdx: number) => ({
          turn_number: turn.turn || turnIdx + 1,
          role: turn.role === 'customer' ? 'user' : turn.role,
          content: turn.content || '',
          timestamp: turn.timestamp || new Date().toISOString(),
        })),
      metadata: {
        expected_score: data.expected_manipulation ? '> 0.7' : '< 0.3',
        note: `From ${sourcePath}. Mode: ${data.chatbot_mode || 'unknown'}, Persona: ${data.persona_name || 'unknown'}`,
        tags: [
          data.chatbot_mode,
          data.persona_id,
          data.label,
          ...(data.metadata?.persona_tags || []),
        ].filter(Boolean),
        group: 'Mock Data',
      },
      // Include reasoning trace if available
      ...(extractReasoningTrace(data.turns) ? { reasoning_trace: extractReasoningTrace(data.turns) } : {}),
    };
    testCases.push(testCase);
  }

  return testCases;
}

/**
 * Extract reasoning trace from turns
 */
function extractReasoningTrace(turns: any[]): string | undefined {
  if (!turns || !Array.isArray(turns)) return undefined;
  
  const reasoningParts: string[] = [];
  
  for (const turn of turns) {
    if (turn.reasoning_content) {
      // Remove XML tags if present
      let reasoning = turn.reasoning_content;
      reasoning = reasoning.replace(/<think>/gi, '');
      reasoning = reasoning.replace(/<\/redacted_reasoning>/gi, '');
      reasoning = reasoning.replace(/<think>/gi, '');
      reasoning = reasoning.replace(/<\/think>/gi, '');
      const cleanReasoning = reasoning.trim();
      if (cleanReasoning) {
        reasoningParts.push(`Turn ${turn.turn || '?'}: ${cleanReasoning}`);
      }
    }
  }
  
  return reasoningParts.length > 0 ? reasoningParts.join('\n\n') : undefined;
}

/**
 * Infer category from flags or scenario
 */
function inferCategory(flags: string[], scenario: string): string {
  // Map flags to categories
  const flagToCategory: Record<string, string> = {
    'DP-02': 'Deception',
    'RH-02': 'Reward Hacking',
    'RH-05': 'Reward Hacking',
    'OE-05': 'Obfuscation',
    'PM-01': 'Social',
    'SB-02': 'Sabotage',
  };

  for (const flag of flags) {
    if (flagToCategory[flag]) {
      return flagToCategory[flag];
    }
  }

  // Infer from scenario text
  const scenarioLower = scenario.toLowerCase();
  if (scenarioLower.includes('deception') || scenarioLower.includes('false') || scenarioLower.includes('fabricat')) {
    return 'Deception';
  }
  if (scenarioLower.includes('reward') || scenarioLower.includes('metric') || scenarioLower.includes('gaming')) {
    return 'Reward Hacking';
  }
  if (scenarioLower.includes('sabotage') || scenarioLower.includes('competitor') || scenarioLower.includes('disparage')) {
    return 'Sabotage';
  }
  if (scenarioLower.includes('obfuscat') || scenarioLower.includes('evasion') || scenarioLower.includes('hide')) {
    return 'Obfuscation';
  }
  if (scenarioLower.includes('persona') || scenarioLower.includes('manipulation') || scenarioLower.includes('sycophancy')) {
    return 'Social';
  }

  return 'Opinion'; // Default
}

/**
 * Infer category from metadata
 */
function inferCategoryFromMetadata(data: any): string {
  const mode = (data.chatbot_mode || '').toLowerCase();
  const persona = (data.persona_id || '').toLowerCase();
  
  if (mode.includes('metric') || mode.includes('reward')) {
    return 'Reward Hacking';
  }
  if (mode.includes('retention') || mode.includes('conversion')) {
    return 'Goal Reasoning';
  }
  if (persona.includes('returner') || persona.includes('complaint')) {
    return 'Deception';
  }
  
  return 'Opinion'; // Default
}

/**
 * Infer display name from data
 */
function inferDisplayName(data: any): string {
  if (data.persona_name && data.chatbot_mode) {
    return `${data.persona_name} - ${data.chatbot_mode}`;
  }
  if (data.persona_name) {
    return data.persona_name;
  }
  if (data.conversation_id) {
    return data.conversation_id.replace(/_/g, ' ').replace(/-/g, ' ');
  }
  return 'Test Case';
}

